// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsletterPreferences.Infrastructure.Persistence;

#nullable disable

namespace NewsletterPreferences.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.CommunicationPreference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CommunicationPreferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EMAIL",
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PHONE",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SMS",
                            Name = "SMS"
                        },
                        new
                        {
                            Id = 4,
                            Code = "POST",
                            Name = "Post"
                        });
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.NewsletterInterest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NewsletterInterests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HOUSES",
                            Name = "Houses"
                        },
                        new
                        {
                            Id = 2,
                            Code = "APARTMENTS",
                            Name = "Apartments"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SHARED_OWNERSHIP",
                            Name = "Shared Ownership"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RENTAL",
                            Name = "Rental"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LAND_SOURCING",
                            Name = "Land Sourcing"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DEV_FINANCE",
                            Name = "Development Finance"
                        },
                        new
                        {
                            Id = 7,
                            Code = "PLANNING_UPDATES",
                            Name = "Planning Updates"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NEW_DEVELOPMENTS",
                            Name = "New Developments"
                        });
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.SubscriberType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriberTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HOME_BUYER",
                            Name = "Home Buyer"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HOME_BUILDER",
                            Name = "Home Builder"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LAND_AGENT",
                            Name = "Land Agent / Land Sourcer"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DEVELOPER",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OTHER",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ConsentTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubscriberTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubscriberTypeId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.SubscriptionCommunicationPreference", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommunicationPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId", "CommunicationPreferenceId");

                    b.HasIndex("CommunicationPreferenceId");

                    b.ToTable("SubscriptionCommunicationPreferences", (string)null);
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.SubscriptionInterest", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewsletterInterestId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId", "NewsletterInterestId");

                    b.HasIndex("NewsletterInterestId");

                    b.ToTable("SubscriptionInterests", (string)null);
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("NewsletterPreferences.Domain.Entities.SubscriberType", "SubscriberType")
                        .WithMany()
                        .HasForeignKey("SubscriberTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriberType");
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.SubscriptionCommunicationPreference", b =>
                {
                    b.HasOne("NewsletterPreferences.Domain.Entities.CommunicationPreference", "CommunicationPreference")
                        .WithMany()
                        .HasForeignKey("CommunicationPreferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewsletterPreferences.Domain.Entities.Subscription", null)
                        .WithMany("CommunicationPreferences")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationPreference");
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.SubscriptionInterest", b =>
                {
                    b.HasOne("NewsletterPreferences.Domain.Entities.NewsletterInterest", "NewsletterInterest")
                        .WithMany()
                        .HasForeignKey("NewsletterInterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewsletterPreferences.Domain.Entities.Subscription", null)
                        .WithMany("Interests")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsletterInterest");
                });

            modelBuilder.Entity("NewsletterPreferences.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("CommunicationPreferences");

                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
